### ISSUE TITLE
Integration with certificates.theodi.org 

### ISSUE THREAD

**Issue by pezholio** [theodi/octopub#1]
Auto generate a certificate for the dataset using the http://certificates.theodi.org API

**Comment by quadrophobiac** [comment]
@pezholio  do you know if the refactor of certificate-factory mentioned in preceding was completed?

**Comment by rachelwilson** [comment]
We're going to close this.  There's a CerificateFactory object used in the octopub code so we can only assume this is no longer an issue.  Do re-open if we've got the wrong end of the stick.
