### ISSUE TITLE
Use CSVw transformation to add JSON view

### ISSUE THREAD

**Issue by pezholio** [theodi/octopub#108]

**Comment by quadrophobiac** [comment]
Attempted to test if this functionality is part of the live codebase, and ran into this error https://github.com/theodi/octopub/issues/486 - as such unable to determine if this ticket can be closed

**Comment by rachelwilson** [comment]
Hi @pezholio and @quadrophobiac.  We're reviewing all the open issues and we're not sure what this one is about.  Could you add a bit more info and context for the newbies?  Otherwise we're probably going to have to close it I'm afraid.
