### ISSUE TITLE
Unable to update existing data file

### ISSUE THREAD

**Issue by leowmjw** [theodi/octopub#114]
When trying to update https://octopub.io/datasets/80/edit; able to change file in dataset that exist (and is published), but is not reflected in the github repo (even after waiting awhile).

When add the same CSV as a new file into the dataset; it works (after a short delay).

**Comment by langphil** [comment]
Attempts to replicate this issue have failed.

Editing and updating of repositories and Jekyll views seems to be working flawlessly, with no time delay.

Closing until this can be replicated successfully and details supplied.
