### ISSUE TITLE
Generated data from CSV causes "Structural problem: Assumed header" validation of CSVLint

### ISSUE THREAD

**Issue by leowmjw** [theodi/octopub#115]
The data package generated using octopub: http://leowmjw.github.io/selangor_adun_2016/data/573ef1d66373766db400013b.html

causes it to fail the "Structural problem: Assumed header" validation: http://csvlint.io/validation/573ef4906373766db400013c

as per described here: https://github.com/theodi/csvlint/issues/176

Solution:

```
...
Content-Type: text/csv;header=present if your file has a header row or Content-Type: text/csv;header=absent if it does not
...
```

**Comment by langphil** [comment]
Issue pertains to [https://github.com/theodi/csvlint](CSV Lint). See issue [https://github.com/theodi/csvlint/issues/176](CSV Lint #176).
