### ISSUE TITLE
Data Package resource has both "path" and url" but can only have one

### ISSUE THREAD

**Issue by danfowler** [theodi/octopub#116]
Hello :).  I noticed an issue with my [Data Package](https://github.com/danfowler/my-first-dataset/blob/gh-pages/datapackage.json):

```
...
 "resources": [
    {
      "url": "http://danfowler.github.io/my-first-dataset/data/data.csv",
      "name": "Periodic Table",
      "mediatype": "text/csv",
      "description": "Periodic Table of the Elements",
      "path": "data/data.csv",
      "schema": {
        "fields": [
...
```

There's been a recent change in the Data Package spec: a `resource` can only have ONE of `path`, `url`, or `data`.  Not to worry, though:

> The path attribute may also be used for Data Packages located online – in this case it determines the resource file’s URL relative to the datapackage.json’s URL.
http://dataprotocols.org/data-packages/#required-fields-1

@rgrp @pwalsh

**Comment by pezholio** [comment]
Thanks for alerting me to this. A fix is on its way up - I've also removed the spurious `datapackage-version`, which I think has been removed from the spec now too.

This won't fix your dataset as it stands, but will fix any that get added in the future. It does raise an interesting question about whether we should regenerate these kinds of things, I'll raise a separate issue for this.
