### ISSUE TITLE
Regenerating files

### ISSUE THREAD

**Issue by pezholio** [theodi/octopub#123]
As mentioned in #116 - I've made some changes to the datapackage to be more in line with the spec. This will fix any newly generated datasets, but not any that were created previously. This raises an interesting question - should we be using Octokit to just generate the files and let the user deal with the repo after that, or should we be regenerating things like the index and the datapackage when we make changes?

For example, there's a few datasets that use an old template, and there are others that are flat out broken. Do we be helpful and regenerate them, or do we just leave them and assume the user will fix?

**Comment by Stephen-Gates** [comment]
My expectation would be that it is either fixed or I'm notified that it's broken and told how to fix.
