### ISSUE TITLE
Preview data structure from data package

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/octopub#125]
Show the structure of the data in a human-readable form. 
E.g. In a table show for each column:
- the column name
- title
- type
- format
- description
- constraints 

Something similar here: 
- OKI [Data Package Viewer](http://data.okfn.org/tools/view)
- [example view](http://data.okfn.org/tools/view?url=http%3A%2F%2Fdata.okfn.org%2Fdata%2FCDECatapult%2FPostcode%2520and%2520demographic%2520data%2520of%2520GP%2520Practices%2520in%2520England%2Fdatapackage.json)

**Comment by Floppy** [comment]
I've got this in some of the early experiments that led to Octopub, so there is code we can take from there. See schemas on http://somethingnew.org.uk/about/finances/.

**Comment by Floppy** [comment]
@jamesjefferies it's actually simpler than I remembered: https://github.com/SomethingNewUK/somethingnewuk.github.io/blob/master/_includes/finances/schemas.html

**Comment by jamesjefferies** [comment]
Cheers @Floppy will take a look :)
