### ISSUE TITLE
Re-assuring statements regarding Octopub GitHub permissions

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/octopub#127]
In signing up for Octopub, this stopped me in my tracks:

<img width="824" alt="screenshot 2016-05-29 09 26 20" src="https://cloud.githubusercontent.com/assets/9379524/15630566/448a4bea-2584-11e6-806d-950e1f7c7d63.png">

Can you make some reassuring statements about what Octopub does and why it needs all these permissions.

**Comment by slowe** [comment]
For me it also wants "Organization access". It stopped me going any further too.

**Comment by Floppy** [comment]
Scope info: https://developer.github.com/v3/oauth/#scopes

The `public_repo` scope doesn't break down any further, unfortunately, so we would still need those wide permissions for public repos, though explanation could certainly be improved.

We only need `repo` to be able to let people create private repositories. This may be unnecessary as I don't think we expose private upload as an option.

I wonder if we can upgrade permissions to include `delete_repo` later if and when the user asks for deletion?

If it's asking for organisation access, we probably don't need that. The `*:org` permissions are just for editing organisations themselves, not the repositories in them.

@pezholio the app is under your account I think; we should change it to be under the ODI organisation at https://github.com/organizations/theodi/settings/applications so that we can group edit it.

**Comment by Floppy** [comment]
Ideally we'd have a `public_repo:create` and similar permissions, but github doesn't break it down that far (yet).

**Comment by pezholio** [comment]
Cool, I've transferred ownership now - can't believe I hadn't done that sooner! So, what we need to do is:

- [ ] Remove the `repo` permissions
- [ ] Remove the `delete_repo` permission
- [ ] Only ask for `delete_repo` permissions if a user tries to delete a dataset
- [ ] Improve the explanation of

I *think* the `*:org` permissions are needed to get a user's non-public organisation memberships, although this could again be something we ask for only if a user needs to publish to an organisation that they haven't made public.

**Comment by Floppy** [comment]
nice one!

**Comment by Floppy** [comment]
I think perhaps the first thing is to just remove the private access bits, and add that back in as an enhancement. There's more thinking to do around it anyway (e.g. private repos and github pages don't make any sense).

**Comment by Floppy** [comment]
Ah, I was thinking it was defined on the app in github, but instead it's here: https://github.com/theodi/octopub/blob/7b9a9c97b62b8e7d53c613f4447e3435a38fd094/config/initializers/omniauth.rb#L2. There must be some defaults as well being added somewhere.

**Comment by Floppy** [comment]
I guess `repo` includes `public_repo`, and perhaps we aren't asking for any `org` permissions. @slowe did it definitely ask you for something extra over and above what's reported above?

**Comment by Stephen-Gates** [comment]
@Floppy I suspect the missing bit is Organization Access that I didn't grab in the screen shot above. 
<img width="852" alt="screenshot 2016-09-20 22 41 43" src="https://cloud.githubusercontent.com/assets/9379524/18670513/aafaeeee-7f83-11e6-9428-2d5876bd8d63.png">

**Comment by Floppy** [comment]
Yep, just realised that myself @Stephen-Gates! I've added some text to the description of the github app. Unfortunately it's doesn't format nicely, but it's *right there* next to the permissions, which I think is the best place. This shot still has private access requested, though I'm removing that in the code as well.

![screen shot 2016-09-20 at 13 45 13](https://cloud.githubusercontent.com/assets/3565/18670611/b030b27c-7f38-11e6-81ba-a2876cd5168f.png)

**Comment by Floppy** [comment]
The organisation access bit isn't something we request ourselves, it's github's UI for letting users choose which organisations to give access to, so we don't have any control over that.

**Comment by Floppy** [comment]
Slightly updated text:

> Octopub is a tool for publishing datasets onto GitHub. In order to upload your datasets, we have to ask for full access to your public repositories; GitHub doesn't support more restricted permissions unfortunately. We ask for your email address in order to let you know when uploads are complete, and we ask for delete permission so that you can easily clean up old datasets from your octopub.io account. Octopub will never change or remove any repositories that you didn't create using Octopub, and will never email you for any purpose other than upload notifications. Full source code for the app is at https://github.com/theodi/octopub.

**Comment by pezholio** [comment]
Nice 👍

**Comment by Floppy** [comment]
With that explanation, do you think we need to do the delayed-delete-permission thing? Which I'm not even sure we can do, and which would certainly be a bit of a faff. We could perhaps file it as a future improvement, but leave as is for now. Thoughts?

**Comment by pezholio** [comment]
I've just logged a new issue - https://github.com/theodi/octopub/issues/187 can we close this do you reckon?

**Comment by Floppy** [comment]
👍 I think so, other participants should feel free to reopen if we've not done enough to satisfy :)
