### ISSUE TITLE
Make Publisher mandatory

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/octopub#128]
Looking at the [example dataset](http://danfowler.github.io/my-first-dataset/) from the [Comma-Chameleon home page](https://comma-chameleon.io), it does not have a Publisher set. When I try to earn an Open Data Certificate for this dataset it just misses out on earning a Bronze certificate because this value is missing.

Consider making Publisher a mandatory value.

<img width="943" alt="screenshot 2016-05-29 10 20 36" src="https://cloud.githubusercontent.com/assets/9379524/15630639/03571114-2587-11e6-844e-db6421e61a03.png">

**Comment by jamesjefferies** [comment]
@Floppy Is it just publisher name which is required, or does it require the publisher URL as well?

**Comment by Floppy** [comment]
Hm, good question. Let's start with just name. Could be something being published personally, for instance, without a URL to refer to.

**Comment by Stephen-Gates** [comment]
Both name and URL are asked for in certificates but only the name is needed to earn a bronze certificate.

**Comment by Floppy** [comment]
Perfect, thanks @Stephen-Gates

**Comment by jamesjefferies** [comment]
Publisher Name is now mandatory
