### ISSUE TITLE
Submission form wipes all responses

### ISSUE THREAD

**Issue by EmilyVacher** [theodi/octopub#130]
When trying to fill in the metadata fields, if Octopub doesn't like something you have entered - it clears the whole form and you have to start again. Time consuming and frustrating. It also doesn't tell you what the problem was.

**Comment by quadrophobiac** [comment]
This seems related to the changes proposed in #198

**Comment by langphil** [comment]
#130 and #198 seem distinct in what they are speaking about. 

I cannot successfully recreate the issue outlined by @EmilyVacher.

Parking this, unless the bug can be identified and recreated.
