### ISSUE TITLE
Octopub claims my CSV is not valid

### ISSUE THREAD

**Issue by EmilyVacher** [theodi/octopub#131]
CSVlint says that the file is valid, Octopub says it's not. Valid data: http://csvlint.io/validation/575acdd463737604c50001b7

**Comment by langphil** [comment]
I've attempted to replicat this and have an invalid CSV Lint warning in both CSV Lint and Octopub - Structural problem: Inconsistent Line Breaks on row 23 

[https://csvlint.io/validation/5a562c84aeb2a70004000066](Link)

<img width="1170" alt="screen shot 2018-01-10 at 16 23 33" src="https://user-images.githubusercontent.com/5029907/34783145-a2f8c330-f622-11e7-8bf6-5a6663803673.png">

**Comment by langphil** [comment]
Closing as I can't successfully replicate. @EmilyVacher
