### ISSUE TITLE
license lookup failing

### ISSUE THREAD

**Issue by Floppy** [theodi/octopub#15]
Using odlifier, it's failing to find licenses for some reason. I suspect the license name changes from a while ago, but I don't know why it's only just happened. For some reason it's causing the build to suddenly fail, but even if I roll back a few versions, it still fails, so... I dunno.

**Comment by quadrophobiac** [comment]
This sounds like its from the git-data-publisher period of this tool, can this issue be closed @Floppy?

**Comment by rachelwilson** [comment]
We're going to close this one because we dont think it's an issue anymore.  Do re-open if we're mistaken.  Thanks.

**Comment by Floppy** [comment]
I think a license changed ID a while back. There is an open PR now on odlifier to handle such cases (written by OKF) but yeah, this can go.
