### ISSUE TITLE
Email users when dataset is created

### ISSUE THREAD

**Issue by pezholio** [theodi/octopub#159]
Creating JSON from large files can sometimes be slow, so people may think something has gone wrong if they're confronted with a spinner for too long. We could redirect people to the dashboard immediately, then trigger an email when the dataset is built. This also means we can send an email with an error if there's a problem, and instructions on how to raise an error, which will mean we don't need to trawl the logs if something goes wrong!

**Comment by pikesley** [comment]
We did it!
