### ISSUE TITLE
CI for data

### ISSUE THREAD

**Issue by pezholio** [theodi/octopub#174]
On all the repos we create, there's a chance that people will want to collaborate on the data outside Octopub. If this happens, we could run CSVlint against the data and return a build status. 

Not entirely sure how this would work entirely, but it might be worth doing at some point in the future.

**Comment by Stephen-Gates** [comment]
@pezholio,  Wouldn't this just be, detect a commit in GitHub, then run tests, and notify of result (via badge on Octopub page)? 

This would be similar to what Open Knowledge do with Good Tables as [described in this blog](http://okfnlabs.org/blog/2016/05/17/automated-data-validation.html).

I thought ODI Labs had done [something similar](https://github.com/theodi/cid).

Am I missing something here?

**Comment by pezholio** [comment]
No, that's pretty much what I imagined. I guess I was thinking more about running the build in Octopub itself, rather than introducing another external dependency like Travis.
