### ISSUE TITLE
Append to file operation

### ISSUE THREAD

**Issue by pezholio** [theodi/octopub#184]
Rather than uploading a brand new file each time, we might want to consider appending new rows to a CSV. Probably just an API endpoint for now.

**Comment by ldodds** [comment]
You could support HTTP PATCH operation on the existing file endpoint in addition to PUT?

You'd need a way to express the change, ideally you'd want to be able to specify a update, append, or delete, but initially you only need to support append. I think there's a few proposals floating around on patch formats.

**Comment by quadrophobiac** [comment]
@pezholio & @ldodds - I know this is asking you to cast your minds back but is 

>uploading a brand new file each time

how both the PUTs of Octopub (https://octopub.io/api#!/datasets/) operate?

**Comment by quadrophobiac** [comment]
Also does this relate to https://github.com/theodi/octopub/issues/114
