### ISSUE TITLE
Can't add a new dataset

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/octopub#188]
I'm logged in. All other pages work fine. But...

![image](https://cloud.githubusercontent.com/assets/9379524/18695140/f9307772-7ff2-11e6-8130-425088bd32f1.png)

**Comment by pezholio** [comment]
Is this when submitting, or just navigating to the /datasets/new page?

**Comment by Stephen-Gates** [comment]
Just going to the page

**Comment by pezholio** [comment]
@Stephen-Gates Any chance you can try now please? I'm watching the logs

**Comment by Stephen-Gates** [comment]
Just failed

**Comment by pezholio** [comment]
Cool, thanks. I think I see the error now:

```
ActionView::Template::Error (GET https://api.github.com/user/memberships/orgs: 403 - You do not have access to organization memberships. // See: https://developer.github.com/v3)
```

@Floppy - could this be related to the PR we merged yesterday?

**Comment by Floppy** [comment]
@pezholio I don't think so, I didn't remove anything about organisations - that didn't change. I'll have a play though. Do you see the same error?

**Comment by Floppy** [comment]
Did you have to revoke permissions?

**Comment by pezholio** [comment]
Nah, just logged out and in again. I think you only see that if permissions change

**Comment by Floppy** [comment]
OK, I see the same now. FFS.

**Comment by Floppy** [comment]
The API call is https://developer.github.com/v3/orgs/members/#list-your-organization-memberships

**Comment by pezholio** [comment]
Oh and that needs `repo` permissions? Grrrr.

**Comment by Floppy** [comment]
I think now having removed `repo`, we might need to explicitly add `read:org`. It's not stated in the docs, but it could be true. I wish the API calls listed the scopes they are available in...

**Comment by pezholio** [comment]
Aaaaaaah. It would help wouldn't it?

**Comment by Floppy** [comment]
Yep, that was it. It should now work. @pezholio @Stephen-Gates can you confirm? Is github's documentation open for PRs, I wonder? :)

**Comment by pezholio** [comment]
That worked for me, but I had to log out and in again. Can we force log people out? I seem to have some vague remembrance that we can do that kind of thing...

**Comment by Floppy** [comment]
Apparently we could, on the console:

`
for user in User.all
  sign_out user
end
`

I'd like to see if it starts working for @Stephen-Gates without relogin though, first. If it doesn't, then we'll force logout for all.

**Comment by Floppy** [comment]
Or just change the secret token. That's the easiest way. https://stackoverflow.com/questions/16406208/how-can-i-reset-all-devise-sessions-so-every-user-has-to-login-again

**Comment by pezholio** [comment]
Cool 👍

**Comment by Stephen-Gates** [comment]
@floppy Worked for me after being asked to re-authorise access. Thanks

**Comment by Floppy** [comment]
@Stephen-Gates ah, but without explicit logout/login? It worked automagically?

**Comment by Stephen-Gates** [comment]
I went back in and got this pop up 
![img_2218](https://cloud.githubusercontent.com/assets/9379524/18708056/53a27a5e-803c-11e6-98ee-80d27105eec9.PNG)

**Comment by Floppy** [comment]
great :D
