### ISSUE TITLE
Octopub experiment scope?

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/octopub#189]
What is the scope of Octopub? I can think of many things I could add but don't want to raise a bunch of issues if they're way out of scope. Some I've raised may already be beyond scope (#124, #125, #126 , #129). 

The [announcement link on readme.md](http://theodi.org/blog/removing-barriers-to-publishing-open-data) goes to earlier work (2014) and some of the future features have been delivered. 

Looking for an update to the article, I [searched theodi.org for "octopub"](http://theodi.org/search?q=octopub) and found [a blank post introducing Octopub](http://theodi.org/introducing-octopub-publish-data-to-the-web-quickly-and-easily) and another on [publishing for non-techies](http://theodi.org/blog/open-data-tools-that-make-publishing-easy).

I think a clear statement on scope would be useful in setting user expectations and help direct more user research #135.

**Comment by Floppy** [comment]
Blank post? Dammit. Will fix.

On the rest, this is a really good question. I won't answer straight away, but wanted to acknowledge the question. Will post back with thoughts.

**Comment by Floppy** [comment]
Ah, that's actually an event - it shouldn't be showing up blank at that URL, it's at http://theodi.org/summit/2016/training-day/sessions/introducing-octopub-publish-data-to-the-web-quickly-and-easily instead. Did Google pick that up @Stephen-Gates? That's disturbing.

**Comment by Stephen-Gates** [comment]
@floppy just did a search on theODI.org

**Comment by olivierthereaux** [comment]
Resolved (hopefully) with new getting-started / about page.
