### ISSUE TITLE
Improvements to /datasets page

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/octopub#190]
This is a collection of ideas for the /datasets page. Happy to split these into individual issues if needed
- search/filter/sort table to help find data or collections of data from the same publisher. 
- Using the URL from a search, a publisher could provide a link to show all their data. (A tiny portal).
- Replace the owner column with publisher name (owners can see all their datasets via /dashboard).
- combine name and link columns. With the extra space gained, add other fields like last updated, update frequency, and a derived overdue for update indicator. Nice spin off is show all publisher datasets overdue for update. 
- show more than 7 datasets per page.

**Comment by olivierthereaux** [comment]
Made obsolete by new version.
