### ISSUE TITLE
Files with "+" in the name don't upload properly

### ISSUE THREAD

**Issue by Floppy** [theodi/octopub#199]
Possibly an encoding thing, or somesuch.

**Comment by pezholio** [comment]
Ah, that's probably related to https://github.com/theodi/octopub/commit/714ebf828f4083197385fb46e5c333658c6087ec - need to do the same thing for files too

**Comment by jamesjefferies** [comment]
Also file names like this: bad URI(is not URI?): ..... a-list-of-some-robots-in-some-films-with-their-socieconomic-class (1).csv
