### ISSUE TITLE
Load test and scale

### ISSUE THREAD

**Issue by Floppy** [theodi/octopub#200]
Improvements to scale to c. 25 users accessing tool at any one time.

NOTE: now looking at maybe only 5 users at a time, also awaiting any other performance/responsiveness issues from FSA

**Comment by Floppy** [comment]
Set up a new frontend at https://dashboard.heroku.com/apps/octopub-loadtest for load testing, so we don't interfere with the real app. Looking at loader.io for testing at the moment.

**Comment by Floppy** [comment]
Test with larger scale datasets too.

**Comment by Floppy** [comment]
@jamesjefferies did you do anything on this while I was off the project?

**Comment by jamesjefferies** [comment]
@Floppy hello! Nope, but following conversations with the client team, I think we decided that the main issue wasn't around concurrent users, more around uploading file issues, i.e. the async issue where the repo isn't created, yet octopub tries to create a branch or push or whatever.

**Comment by Floppy** [comment]
OK, great. I'll close this for now, we can revisit later if actual load becomes an issue. That explanation sounds perfectly reasonable.
