### ISSUE TITLE
Add multiple user roles

### ISSUE THREAD

**Issue by Floppy** [theodi/octopub#201]
Decouple Octopub users from GitHub users; individual users shouldn't have to have GitHub accounts

Roles:
* Publishers(?) can create datasets
* Editors(?) can add data to existing datasets

**Comment by jamesjefferies** [comment]
Just thinking about this:

As a logged in GitHub user, I can currently

1) Create a dataset and/or schema for my GitHub user
2) Create a dataset and/or schema for my GitHub organisations which I have permissions for (?)

Q: Does this functionality remain? I'm assuming yes

For non-GitHub users and roles - I'm not sure if this changes now with schemas or what, but is this the kind of thing we are looking at. Two roles, Editor and Publisher:

Editor can:

a) create datasets and/or schemas
b) edit existing datasets

Publishers can:

a) create datasets and/or schema

Or is there more to it than this?

**Comment by jamesjefferies** [comment]
Also, where does the dataset and jekyll pages get created if the user isn't a GitHub user? *scratches head*

**Comment by jamesjefferies** [comment]
- [ ] Add devise to application
- [ ] Allow user to log in with either GitHub or Devise credentials
- [ ] Update UI to let Devise users read only initially
- [ ] Once #275 is complete allow Devise users to push data to, say, S3

**Comment by jamesjefferies** [comment]
Revising the scope for this:

- [ ] Add new roles, Publisher, superuser, Admin
- [ ] Introduce new UI for viewing users, amending user roles

**Comment by jamesjefferies** [comment]
Marking this as done, but other issues raised for further detail for different roles
