### ISSUE TITLE
Schema creation tool

### ISSUE THREAD

**Issue by Floppy** [theodi/octopub#202]
Same as theodi/csvlint#278, we want to be able to create schemas in some simple way. It could even be a link through to the functionality added in theodi/csvlint#278, perhaps.

**Comment by Floppy** [comment]
Deprecates #183. Could be done automatically as part of publishing, as suggested there.

**Comment by jamesjefferies** [comment]
This now references a full-on schema creation tool, as opposed to just creating from an example file as in #276

**Comment by jamesjefferies** [comment]
Schemas can now have their constraints edited, but there is currently no functionality for, for example, adding a new schema field.

**Comment by Floppy** [comment]
Closing this as done, further requirements can be added separately.
