### ISSUE TITLE
Publish privately

### ISSUE THREAD

**Issue by Floppy** [theodi/octopub#204]
We want the ability to publish privately in a sort of "preview" mode. GitHub pages are public even if the repo is private, which is potentially problematic there. We might need a different backend, or to somehow disable gh-pages and instead publish the preview pages elsewhere.

**Comment by Floppy** [comment]
A thought occurs. Is security by obscurity enough here? If the repository is private, and the dataset isn't listed in the dataset list on the site (which it shouldn't be), the path to the published page won't be public, so won't be discoverable. Having said that though, someone's bound to leak one at some point, or they could be guessable. Depends what level of safety we need.

**Comment by Floppy** [comment]
Things that definitely need doing whatever, though:

* [ ] create and publish to a private github repo
* [ ] add a private field in the DB
* [ ] only show private datasets to the user that owns them (with a padlock in the list maybe)

**Comment by Floppy** [comment]
OK, discussed with client and obscurity is not enough. Private data must not be publicly available on the web even if obscured.

**Comment by Floppy** [comment]
Another update from client discussion. There actually isn't a definite need for HTML views of private data at this point, so we can avoid the problem by only generating the Jekyll site when things are made public.

This will need a bit of a refactor, but will keep things simple. Basically publication is a two-step process. 1) data publishing and then 2) HTML/certificate/portal publishing. 2 can happen either immediately for public data or later on for private data being made public.

**Comment by Floppy** [comment]
Adding to above list:

* [ ] Refactor HTML creation into a post-publishing step along with certification
* [ ] Trigger HTML generation at same time as certification

**Comment by Floppy** [comment]
So, from Github support, the API doesn't currently allow setting of the gh-pages status or branch, so we'll have to stick to a later commit for public pages. Might even need to change branch name, we'll see.

**Comment by Floppy** [comment]
With #222 in place, jekyll publishing is refactored into separate methods from data publishing. Currently they are called together, but now we can move on to moving Jekyll into a separate post-upload step.

**Comment by jamesjefferies** [comment]
I think this all basically done now - users can push to a private GitHub repo (with no jekyll files) or to a local Octopub repo (which is, in effect S3).
