### ISSUE TITLE
Submit dataset automatically into data.gov.uk

### ISSUE THREAD

**Issue by Floppy** [theodi/octopub#206]
Or presumably any CKAN instance. Publishing should submit a new item, and updating should ping with an update.

**Comment by Floppy** [comment]
Public datasets only, or should happen when a dataset is made public, like certification.

**Comment by jamesjefferies** [comment]
Looks like this is a fork of the original RubyGem - and is a bit more up to date: 

https://github.com/fishpercolator/CKAN

**Comment by jamesjefferies** [comment]
This is also useful by fishpercolator up in Leeds: https://medium.com/@fishpercolator/accessing-open-data-from-ruby-code-d4f07242cc37#.31fatq9ra

**Comment by jamesjefferies** [comment]
Just looking at running a local CKAN instance using either Docker (which works with Travis) or Vagrant (which doesn't) - this can be used to develop/test against.

**Comment by jamesjefferies** [comment]
Out of Scope for FSA work for now
