### ISSUE TITLE
Update to rails 5

### ISSUE THREAD

**Issue by Floppy** [theodi/octopub#207]

**Comment by Floppy** [comment]
Might as well bump .ruby-version to 2.4 at the same time.

**Comment by Floppy** [comment]
oh, and in travis.yml

**Comment by jamesjefferies** [comment]
Yep, makes sense to do the big bumps!

**Comment by jamesjefferies** [comment]
Working on Rails update first - Rails 4.2 is ok, just working through Rails 5 issues now..

**Comment by jamesjefferies** [comment]
All tests but one now passing. The one which is failing is related to User storing the ```org_dataset_ids``` as a text array. This means (under Rails 5 anyway) that when you retrieve the ids, they are of the form ```[ "1", "2", "3" ]``` rather than what the tests expect which is ```[ 1, 2, 3 ]```. I need to look at this a bit more to see whether we should actually just convert the ideas to ints on retrieval... Probably simplest solution which would give us passing tests.

**Comment by Floppy** [comment]
Or store it as an int array - but I guess that would affect currently-stored data.

**Comment by Floppy** [comment]
or is it that Rails 5 is storing it as a string array rather than converting beforehand, for some reason? I can check the existing DB to see what's in there... asuming it's a DB field?

**Comment by jamesjefferies** [comment]
It is a DB field - I think that postgres stores the array as text, which is ok, but it should be storing [1,2,3] - but maybe something weird is going on.. I'll check tomorrow with fresh eyes and a (hopefully) good night's sleep!

**Comment by jamesjefferies** [comment]
Rails 5 update with the org_dataset_ids column produces a mismatch of types

In my environment (Postgres 9.5) when the org_dataset_ids are saved as an array of integers (in an text/array column) they are returned as an array of string integers. This causes a test to fail.

On further investigation, it looks like production Octopub is running on Postgres 9.3 which may explain the discrepancy.

Also, it looks like the column, whilst populated, was added in June 2016 and isn't actually used by the application.

It's possible therefore that it should actually be removed!

For now, the test converts the array of strings to an array of ints and now passes

https://github.com/theodi/octopub/commit/8d7b24d1eafd332365699d0869d69cff4a7ca80a

Possible actions

* Update production Postgres to >= 9.5
* Remove unused column and code if not actually required

**Comment by jamesjefferies** [comment]
Apart from that, all tests now passing with Rails 5 and Ruby 4.2

Before creating a pull request I want to run through the application properly in a browser to make sure things look ok. So next task is getting that working properly (I assume with a github repo and S3 to test against)

**Comment by Floppy** [comment]
OK, nice one. Can you file those two followups as separate tickets, and we can come back to them later maybe.
