### ISSUE TITLE
404 on view for a dataset published through Octopus

### ISSUE THREAD

**Issue by peterkwells** [theodi/octopub#243]
See 

https://jmef.github.io/list-of-entertaining-data-related-youtube-videos/

Click view and get 404. Download works fine. Data looks fine.

**Comment by jamesjefferies** [comment]
Hmm, the markdown file has been deleted: 

https://github.com/JmeF/list-of-entertaining-data-related-youtube-videos/commit/1a16c6648778c8c8440fa3cf37cbc0e3cd193aef

I'm not sure if this was a user action or something done automatically?

**Comment by Floppy** [comment]
I think Jamie published it during the time there was an error, and did some manual fixing. Perhaps he deleted it then, by accident.

**Comment by jamesjefferies** [comment]
Ok @JmeF has fixed it for us, no longer 404s - https://jmef.github.io/list-of-entertaining-data-related-youtube-videos/data/list-of-entertaining-data-related-youtube-videos-january-2017
