### ISSUE TITLE
Can't add another data file - button does nothing

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/octopub#256]
After adding https://stephen-gates.github.io/public-transport-schedules-for-south-east-queensland/ via Octopub, I went back to add more datasets and schemas. 

I pressed the `+ Add another data file` button within https://octopub.io/datasets/301/edit but nothing happened.

(Trying to publish what I've already done [here](https://github.com/Stephen-Gates/GTFS) but using Octopub)

**Comment by jamesjefferies** [comment]
This may have broken with the changes to the Add Dataset page - it's on my list to look at tomorrow.

**Comment by jamesjefferies** [comment]
This fix has been now pushed to production.
