### ISSUE TITLE
Orphan schema

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/octopub#258]
On octopub, I have a schema in my list of schemas called Agency. It is not in GitHub. It may of been created when I tried to add a private version of the GTFS public transport data. I never received an email saying that the repository was created. How do I delete that schema?

**Comment by jamesjefferies** [comment]
Hmm, ultimately we could do with edit and delete functionality in the User Interface for Schemas. For now though, would you like us to delete it from the database?

**Comment by Stephen-Gates** [comment]
Yes please @jamesjefferies. Thanks

**Comment by jamesjefferies** [comment]
I've deleted that schema for you now - @Stephen-Gates it's possible you have found an edge case where you create a private version and something went wrong. I'll leave this here for now for further investigation at some point!

**Comment by jamesjefferies** [comment]
This hasn't re-occurred and users can now delete their own Schemas if required.
