### ISSUE TITLE
Long, weird CSV not being handled well in display

### ISSUE THREAD

**Issue by peterkwells** [theodi/octopub#279]
My dataset of Ofcom data needs caution text, I created as a standalone, single-field file in CSV. The data doesn't display nicely in github pages. Should this be supported?

https://peterkwells.github.io/uk-attitudes-to-offensive-language-and-gestures-data/data/caution/

**Comment by rachelwilson** [comment]
Hi Peter (we're reviewing our bugs and finally came round to this one).  The thing is, CSV doesn't work very well as a display format.  And we dont have any control over github pages and its display of long CSV fields.  So we're going to close this issue in Github.  But we're grateful for you for pushing our limits!
