### ISSUE TITLE
Pusher errors

### ISSUE THREAD

**Issue by pezholio** [theodi/octopub#326]
When trying to do anything which requires Pusher (create datasets, refresh etc), I get the error:
```
Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":4001,"message":"Could not find app by key 5638e7c8fc42dee84d4f. Perhaps you're connecting to the wrong cluster."}}}
``` 

in the console. Probs something to do with the Pusher config in Heroku

**Comment by jamesjefferies** [comment]
Hmm, I had to add the `PUSHER_CLUSTER` to the environment variables (with corresponding code) to get it to work locally as pusher defaults to the US cluster or something, whereas my development pusher instance defaulted to EU. I decided that Octopub.io would probably also be EU as it's socket URL includes eu in it.. Either it isn't in the EU cluster or something else is broken with it I. I don't have access to the app in Pusher, but I'll check to see if @Floppy can confirm which cluster it is running in and make sure that Heroku is configured correctly.

**Comment by Floppy** [comment]
Yep, both pusher and octopub's heroku are running in the EU cluster.

**Comment by jamesjefferies** [comment]
Thanks, yep, I can see what it is, Pusher cluster can't be retrieved from the `Pusher` object, so in dev I plop it in rails config. It needs to be in rails config for all environments... will fix it now.

**Comment by jamesjefferies** [comment]
Ok, should be fixed now, re-open the ticket if it's still misbehaving - thanks @pezholio @Floppy :)

**Comment by pezholio** [comment]
Sweet, ta 👍
