### ISSUE TITLE
Erroneous 'Who will be able to see your data?' in the form

### ISSUE THREAD

**Issue by pezholio** [theodi/octopub#344]
For some reason, the text 'Who will be able to see your data?' appears below the public and private part of the form, as below:

![fireshot capture 255 - octopub - https___octopub io_datasets_new](https://cloud.githubusercontent.com/assets/109774/24243427/02210f54-0fb3-11e7-9f4f-94194eb69a45.png)

**Comment by jamesjefferies** [comment]
Yes, that's bootstrap adding the 'help' section at the end in a lighter tone. I think in this case it *isn't* helpful! This has changed from a select box to a radio button by the way as there will be a 3rd option (currently a WIP PR) for private local storage (in S3) for users who do not have paid GitHub accounts.

**Comment by pezholio** [comment]
Ah ha!
