### ISSUE TITLE
Hide optional schema in form

### ISSUE THREAD

**Issue by pezholio** [theodi/octopub#345]
It's not immediately obvious that I can add more than one file, as I have to scroll down past the schema part, which might not be relevant. Can we have it so the schema is hidden by default, and only shown if the user chooses to add a schema? Would also be good if the file and schema were grouped together now, as they have a 1-1 relationship

**Comment by pezholio** [comment]
Also, the text still says `Provide an optional schema that all data files must adhere to`

**Comment by jamesjefferies** [comment]
Yep, same as what I've been thinking really, I've been thinking about some updates to how that works but I've been focussing on requirements first - would be relatively straightforward to do a bit of showey/hidey for the schema section though, so I'll see how I get on :)

**Comment by langphil** [comment]
Closed. Work is happening as part of UX focus. Documentation of this work is happening within that work structure.
