### ISSUE TITLE
Admin users can grant access to the FSA instance - not any old GitHub user can use the FSA one.

### ISSUE THREAD

**Issue by jamesjefferies** [theodi/octopub#349]

**Comment by jamesjefferies** [comment]
The way I see this working is base don an Environment Variable or feature flag as it isn't required on the main ```octopub.io``` instance.

If set:

- User logs in for the first time, but their account is flagged as ```on-hold``` or ```inactive``` or something
- Administrator can see a list of those users (possibly get's emailed the info?)
- Admin can then activate their account giving them normal access

- Application needs to check whether user is *logged-in* and *activated*

**Comment by Floppy** [comment]
My plan for this is to add an optional DEFAULT_ROLE environment variable, so that users can by default be given no roles. Then I need to enforce that only publishers can do things, and do a decent error message.

**Comment by Floppy** [comment]
That default will be a new "guest" role.
