### ISSUE TITLE
additional column to indicate 404 missing

### ISSUE THREAD

**Issue by quadrophobiac** [theodi/octopub#374]
an additional column that can indicate dead links?
not sure how this would work - maybe some integration with the badges that CSVlint produces?
e.g. http://jargonautical.github.io/ancient-trees-plymouth/

**Comment by quadrophobiac** [comment]
possible duplication #112

**Comment by jamesjefferies** [comment]
This is a good idea and would be helpful, you might need a regular job to run which checks for broken links to repositories, overnight say, and marks those which now have a dead link.

**Comment by Floppy** [comment]
* [ ] Add a field to the DB to record the online state of a dataset
* [ ] Write a rake task to check and update that field
* [ ] Add the rake task to the heroku scheduler to run regularly
* [ ] Update the list UI to remove the link or otherwise indicate deadness for datasets that have gone away.

**Comment by quadrophobiac** [comment]
current progress is here https://github.com/theodi/octopub/tree/indicate-404-datasets-with-list-symbol
I have not written any additional tests for these changes because I want to get feedback on what the best way to include the additional *'dead link'* information at the user interface is. Current changes - including this information as an additional column in the dataset view - break some existing tests due to those tests using table cells as means of verifying if test conditions pass. Therefore I deem a sanity check on what to do with this change is advisable before writing more tests for an addition that might be subject to revision
per above checklist the heroku scheduler stuff is pending a pairing session @Floppy

**Comment by quadrophobiac** [comment]
warning triangle alongside URL in Name column, resource status message as hover/tooltip

**Comment by Floppy** [comment]
Add http://fontawesome.io/icon/exclamation-triangle/ after the dataset name, and display information as a tooltip, perhaps.

**Comment by quadrophobiac** [comment]
while this has been merged in an additional cosmetic change to indicate the name of the since deprecated dataset is probably a better user experience
