### ISSUE TITLE
How to make a Private dataset Public?

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/octopub#401]
I've been experimenting with Octopub and published a private dataset https://octopub.io/datasets/321/dataset_files 

I can't see how to make it public. Has this been implemented?

**Comment by jamesjefferies** [comment]
You're right @Stephen-Gates the functionality is all there behind the scenes, but I didn't finish the UI - just working on it now, PR imminent.

**Comment by quadrophobiac** [comment]
@jamesjefferies which PR were you referring to? Off the top of my head I'm pretty sure the functionality described at the outset has now been implemented - is this issue good to close?

**Comment by jamesjefferies** [comment]
@quadrophobiac howdy! I think it was #402 ! Which has been merged :)

**Comment by quadrophobiac** [comment]
Ace thanks @jamesjefferies James
