### ISSUE TITLE
Addition of new element to existing dataset

### ISSUE THREAD

**Issue by peterkwells** [theodi/octopub#403]
Feedback from FSA. New functionality looks good but:

"only concern is regarding the addition of a new element to an existing dataset.
 
In this situation the system is defaulting to ‘no schema required’.
 
It would be our preference that the default in this scenario would be the same schema as the original dataset, with the option to select another (or indeed ‘no schema required’) from the drop down list."

Thoughts?

**Comment by Floppy** [comment]
Should be fine. Will do it today.
