### ISSUE TITLE
Admins not able to edit other user's datasets

### ISSUE THREAD

**Issue by peterkwells** [theodi/octopub#406]
(Feedback from FSA phase 3 testing.)

**Comment by Floppy** [comment]
Similar to #407, but this seems more of an enhancement for the roadmap. Who decides who should be able to edit a dataset?

**Comment by quadrophobiac** [comment]
I have added this to the main labs roadmap on [this card](https://trello.com/c/rbOQlfvW/55-grant-dataset-edit-permissions-to-other-users) - uncertain if there is another roadmap @Floppy. Can I close this ticket?

**Comment by Floppy** [comment]
The request here is actually that admin users should be able to edit other users' datasets, which seems reasonable to me.

**Comment by Floppy** [comment]
Refined in #551
