### ISSUE TITLE
Not able to use schemas added by another user

### ISSUE THREAD

**Issue by peterkwells** [theodi/octopub#407]
(Feedback from FSA phase 3 testing)

**Comment by Floppy** [comment]
What is the desired behaviour here? 

1. Should any user be allowed to use any schema that has been uploaded to the octopub instance?
2. Is that desirable in just the FSA private-instance case, or on octopub.io as well?
3. Should logged-out users be able to browse uploaded schemas?

**Comment by Floppy** [comment]
Also, I am not sure if this is a bug or intended behaviour. @peterkwells do you know any recent background on the feature?

**Comment by Floppy** [comment]
I'm popping it in as a bug for now, as it seems like something that really should be supported.

**Comment by peterkwells** [comment]
Have passed questions to FSA but would be ideal if we could suggest some behaviour too based on knowledge of user needs

**Comment by Floppy** [comment]
I'd like to propose a solution to this:

A schema will have a "public" flag, which will allow any user to access or use it. They won't share ownership, but will be able to search for and use the schema. The flag will be false by default.

Thoughts?

**Comment by Floppy** [comment]
Oh, and schemas should only be visible to logged-in users. Basically this is a fix that allows some level of public schema sharing without impacting the existing behaviour much.

**Comment by quadrophobiac** [comment]
@Floppy schema search sounds like a good addition to the roadmap

**Comment by Floppy** [comment]
@quadrophobiac related to that: #409

**Comment by quadrophobiac** [comment]
have added this to the Roadmap under the Next Up section https://trello.com/b/2xc7Q0kd/labs-public-toolbox-roadmap?menu=filter&filter=label:Octopub

**Comment by Floppy** [comment]
FSA have asked for this in the work I'm doing for them - any thoughts on my idea? It won't take me long to implement...

**Comment by quadrophobiac** [comment]
Yeah I think this is a really good idea

**Comment by quadrophobiac** [comment]
ergo for it

**Comment by Floppy** [comment]
codito ergo sum
