### ISSUE TITLE
Failure when adding a schema through ‘Dataset file schema’ tab

### ISSUE THREAD

**Issue by peterkwells** [theodi/octopub#408]
(Feedback from FSA phase 3 testing)

When adding a schema through ‘Dataset file schema’ tab it errors with the below message, however the schema is available to pick from the list.

<img width="803" alt="screen shot 2017-04-20 at 16 46 22" src="https://cloud.githubusercontent.com/assets/6670237/25239769/ec1de2b2-25e8-11e7-8d7f-8b2d0c7aa7f5.png">

**Comment by Floppy** [comment]
Probably, seeing as the schema did in fact upload, a simple rendering bug.

**Comment by Floppy** [comment]
Strange this one, I can't replicate it either locally, on octopub.io, or on the FSA instance. Can we confirm with them that it's still happening?

**Comment by peterkwells** [comment]
Question posed to client, will update when I get a response

**Comment by peterkwells** [comment]
Client still getting same issue, working fine for me. Trying to speak on phone to walk through the steps

**Comment by peterkwells** [comment]
@Floppy it's still occurring. This is the URL for the error message https://fsa-octopub-staging.herokuapp.com/dataset_file_schemas

**Comment by Floppy** [comment]
Comment from John at FSA: "A member of staff has now just tested this twice and doesn’t seem to be having any issues so I’m hoping this has been sorted."

I'll leave it open until tomorrow when I'm spending the day with them, but I think this might have gone away.

**Comment by Floppy** [comment]
Nope - they've found the schema that breaks it, so I now have it replicated. Hurrah!

**Comment by Floppy** [comment]
And replicated locally too. Error:

```
unknown attribute 'date_pattern' for SchemaConstraint.
```

**Comment by Floppy** [comment]
Minimal test schema:

[date_pattern_test_case.json.txt](https://github.com/theodi/octopub/files/1207637/date_pattern_test_case.json.txt)

**Comment by Floppy** [comment]
```
{
	"fields": [
		{
			"name": "Date",
			"title": "Date",
			"constraints": {
				"required": false,
				"type": "http://www.w3.org/2001/XMLSchema#date", "datePattern": "%Y-%m-%d"
			}
		}
	]
}
```

**Comment by Floppy** [comment]
So `datePattern` is specified in http://csvlint.io/about, so it should be at least conformant to that, though it might be diverged from the standard a bit.

**Comment by Floppy** [comment]
Ah, so this seems simple. `SchemaConstraint` doesn't have a field called `date_pattern`, which it should have to store this attribute. Just needs adding in a migration.

**Comment by Floppy** [comment]
Verified fixed locally, awaiting merge and deployment.
