### ISSUE TITLE
If a CSV has any blank fields the infer dataset file schema does not work

### ISSUE THREAD

**Issue by peterkwells** [theodi/octopub#410]
(Feedback from FSA phase 3)

![Uploading Screen Shot 2017-04-20 at 16.52.27.png…]()

**Comment by Floppy** [comment]
This should be handled, I'll look into it.

**Comment by Floppy** [comment]
Confirmed: 

<img width="968" alt="screen shot 2017-05-04 at 15 10 58" src="https://cloud.githubusercontent.com/assets/3565/25707592/f338a052-30db-11e7-8831-b4c46a94bd04.png">

**Comment by Floppy** [comment]
thanks, tooltips. Thooltips.

**Comment by Floppy** [comment]
I'm chasing this down, but I can't get it to replicate in tests yet, which also makes me worry about at least one other test.

**Comment by Floppy** [comment]
OK, worked out why the mocking isn't working. At least one other test isn't testing correctly because of this.

**Comment by Floppy** [comment]
Cryptic.

**Comment by Floppy** [comment]
OK replicated a failing test for this in #425. The actual error it seems is inside the `jsontableschema` gem, so now I have this isolated, I'll dig down into there and fix it. Baby steps.

**Comment by Floppy** [comment]
Fix is in #425, just waiting for review and then I'll merge it in and deploy.

**Comment by peterkwells** [comment]
Reported to FSA and asked them to retest
