### ISSUE TITLE
Retain original JSON schema builder?

### ISSUE THREAD

**Issue by peterkwells** [theodi/octopub#411]
(Feedback from FSA phase 3)

"All of the team members agree that the original JSON Schema Builder (https://odileeds.github.io/JSONSchema/) is much more user friendly and intuitive than the one integrated into Octopub. As such we would like to continue to use this one. Can you confirm that this will still be available going forward and that the intention is not for this to be replaced by the integrated functionality?"

**Comment by Floppy** [comment]
We don't intend to replace the Leeds schema builder, though obviously we'd like to continue developing the version in Octopub to make it more user friendly. That's something for the future roadmap, I think.
