### ISSUE TITLE
missing email confirmation when a new dataset is added to Octopub

### ISSUE THREAD

**Issue by peterkwells** [theodi/octopub#412]
(feedback from FSA phase 3 testing)

"When Phase 1 originally went live, we would receive email confirmation whenever a new dataset was added to Octopub. This email confirmation is no longer being received in the live instance."

**Comment by Floppy** [comment]
This is a definite bug, I'll investigate.

**Comment by Floppy** [comment]
I suspect this might have been down to the mail queue at the ODI end being blocked. I'll investigate...

**Comment by Floppy** [comment]
OK, so yes, the FSA instances are using the ODI mandrill connection to deliver emails, which is getting regularly blocked by spambots attacking open data certificates. That's causing a number of parallel issues as well.

**Comment by peterkwells** [comment]
Reported to FSA and asked them to retest
