### ISSUE TITLE
Indicate Beta Status

### ISSUE THREAD

**Issue by quadrophobiac** [theodi/octopub#419]

**Comment by quadrophobiac** [comment]
@Floppy was just thinking - should the indicator of beta status be conditional in the case of Octopub given that FSA have a fork from this codebase? What's the conventional thing to do in this instance - should all forks retain beta status OR should beta status only exist on parent codebase?

**Comment by Floppy** [comment]
I suspect FSA's stylesheet in their fork doesn't show any status anyway. I'd consider it only applying to the master codebase.

**Comment by rachelwilson** [comment]
Implemented in Octopub v2
