### ISSUE TITLE
Limit filetypes to CSV

### ISSUE THREAD

**Issue by pezholio** [theodi/octopub#49]
Any non-CSV file can cause 'issues' :confused:

**Comment by langphil** [comment]
Validation in place on the front end. Needs an Active Record validation on the DB to restrict filetype being written.

**Comment by olivierthereaux** [comment]
Scope of tool growing beyond CSV. There will need to be extra logic to deal with multiple data formats (e.g. not send all to csvlint) but this issue is moot.
