### ISSUE TITLE
Mixed content warnings

### ISSUE THREAD

**Issue by chris48s** [theodi/octopub#525]
### Expected Behaviour
> What should happen?

All content should be loaded over HTTPs

### Current Behaviour (for problems)
> What currently happens that isn't expected behaviour?

Mixed content/unsafe script warnings are issued from sites generated with Octopub. I think this is due to recent changes in GitHub pages - until relatively recently GH pages didn't even support HTTPS - now it is the default.

Firefox:
![firefox](https://user-images.githubusercontent.com/6025893/28799417-7458758c-7640-11e7-9fcf-cfd4b60364a8.png)

Chromium:
![chrome](https://user-images.githubusercontent.com/6025893/28799424-776f5308-7640-11e7-9c29-2d6576142dfc.png)

### Steps to Reproduce (for problems)
> Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant
1. Upload a dataset with Octopub
2. Visit site in a web browser
3. Check your address bar for warnings

### Your Environment
> Include as many relevant details about the environment you experienced the bug in - this will help us resolve the bug more expediently

Screenshots provided above are from Firefox 54 on Ubuntu and Chromium Stable 59 on Ubuntu but results should reproduce on most current browser/OS setups

**Comment by quadrophobiac** [comment]
thanks for bringing this to our attention @chris48s

**Comment by chris48s** [comment]
@andylolz has usefully worked out the cause of this - its the CSVlint images. see:
https://github.com/DemocracyClub/wheredoivote-usage-june-2017/pull/1/files

**Comment by quadrophobiac** [comment]
Hey @chris48s, I've extended an Octopub team invite to @andylolz and I wanted to extend the same to yourself, really appreciate you taking time to input on this project and I'd like you to have push access to this repository henceforth - hoping to continue to work together on these tools!

**Comment by chris48s** [comment]
thanks :)
