### ISSUE TITLE
navbar-header link should target dataset index not username.github.io

### ISSUE THREAD

**Issue by chris48s** [theodi/octopub#526]
### Desired Behaviour (for enhancement suggestions only)
> if relevant include images or hyperlinks to other resources that clarify the enhancement you're seeking

`navbar-header` link should link back to dataset/sub-site index by default, not `username.github.io`

### Current Behaviour (for problems)
> What currently happens that isn't expected behaviour?

`navbar-header` links back to root of `username.github.io`

### Steps to Reproduce (for problems)
> Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant

If I look at [this dataset](https://bobharper1.github.io/uk-government-cats-training-set/data/main-list-of-cats/) (for example) the title link 'UK Government Cats - Training Set' links to https://bobharper1.github.io/ which in this case is a 404. It would be more natural for this to link back to the [dataset index]( https://bobharper1.github.io/uk-government-cats-training-set/)

In a case like [this dataset](https://stephen-gates.github.io/comma-chameleon-release-downloads/data/comma-chameleon-release-downloads/) (for example) its a bit less odd because 'Comma Chameleon Release Downloads' is a link to something that actually exists but it would still make more sense for it to link to https://stephen-gates.github.io/comma-chameleon-release-downloads/ instead of https://stephen-gates.github.io/

On [this dataset](https://democracyclub.github.io/wheredoivote-usage-june-2017/data/wheredoivote-usage-june-2017/) I've [edited](https://github.com/DemocracyClub/wheredoivote-usage-june-2017/commit/12e4144b039d31c561aa84b20543487276adfd45) the link to get the desired behaviour but I think this should be the default.

### Your Environment
> Include as many relevant details about the environment you experienced the bug in - this will help us resolve the bug more expediently

platform-independent

**Comment by quadrophobiac** [comment]
@Floppy what do you think about this change in UI?

**Comment by Floppy** [comment]
Yeah, that makes sense. It's daft to link to something unknown, outside the remit of the site.
