### ISSUE TITLE
Test suite fails for all my pull requests :'(

### ISSUE THREAD

**Issue by andylolz** [theodi/octopub#541]
For all my PRs to this repo, tests that involve `<GITHUB_USER>` fail, suggesting the `GITHUB_USER` env variable isn’t being set.

Comparing the config from [a dependabot PR](https://travis-ci.org/theodi/octopub/jobs/262121976/config) to [one of mine](https://travis-ci.org/theodi/octopub/jobs/262159686/config) confirms that `global_env` is not set :( For the dependabot PR, the config JSON includes the following line:

```
"global_env": "GITHUB_KEY=[secure] GITHUB_SECRET=[secure] GITHUB_USER=[secure] BASE_URI=[secure] ODC_USERNAME=[secure] ODC_API_KEY=[secure] GITHUB_TOKEN=[secure] S3_BUCKET=[secure] AWS_ACCESS_KEY_ID=[secure] AWS_SECRET_ACCESS_KEY=[secure] S3_BUCKET=[secure] AWS_ACCESS_KEY_ID=[secure] AWS_SECRET_ACCESS_KEY=[secure]"
```

…whereas for mine, it’s:

```
"global_env": null
```

I can recreate the problem locally by setting/unsetting `GITHUB_USER` in my .env file. Tests pass when it’s set; they fail when it’s unset.

Similarly, if I enable travis on my fork, manually set the `GITHUB_USER` environment variable in travis settings, all the relevant branches pass:
https://travis-ci.org/andylolz/octopub/branches

It doesn’t look like this is something I have the power to fix… But please do let me know if I’m doing something wrong!

**Comment by Floppy** [comment]
`GITHUB_USER` was an old env var used for build tagging in Travis. The app doesn't actually use it, but it's got embedded into a bunch of the tests. I can clean that up, give me a few minutes.

**Comment by andylolz** [comment]
> The app doesn't actually use it

Yeah, I spotted that! NB it’s also included in the README.

**Comment by Floppy** [comment]
cleaned up in #543
