### ISSUE TITLE
Schema creator produces different schema from the ODI Leeds one

### ISSUE THREAD

**Issue by Floppy** [theodi/octopub#555]
Two examples attached. The Octopub version doesn't seem to be using as many features.
[BetterTrainingForSaferFood_OctoPub.json.txt](https://github.com/theodi/octopub/files/1211491/BetterTrainingForSaferFood_OctoPub.json.txt)
[BetterTrainingForSaferFood.json.txt](https://github.com/theodi/octopub/files/1211492/BetterTrainingForSaferFood.json.txt)

**Comment by Floppy** [comment]
Also: schema editor on octopub doesn't show datePattern.

**Comment by Stephen-Gates** [comment]
I don't think the Leeds schema is following the v1.0 specification http://specs.frictionlessdata.io/table-schema/#field-descriptors

**Comment by Floppy** [comment]
Yes, that's it. So Octopub is more correct. I will communicate that to the client :)
