### ISSUE TITLE
Cannot make github private datasets public

### ISSUE THREAD

**Issue by Floppy** [theodi/octopub#557]
Currently if you have a private dataset on github, you don't get the option to make it public. You do get it for local private datasets, however. @jamesjefferies do you remember why this might be so?

**Comment by jamesjefferies** [comment]
Hmm, I'd have thought it would be the other way around! A private github repo can be made public, but a private local dataset can only be made public if it is published to a public github repo. Hmm, if it is the way around you as you suggest, then I think it might just be an unfinished thing... @Floppy

**Comment by olivierthereaux** [comment]
Made obsolete by new scope (and deprecation of private repo) of octopub
