### ISSUE TITLE
Share schemas with specific users

### ISSUE THREAD

**Issue by Floppy** [theodi/octopub#558]
Once we can make schemas public (coming in #548), we could do with making schemas only accessible by specified users.

**Comment by quadrophobiac** [comment]
will this operate at an organisational (IE Github teams as a proxy for an org) level?

**Comment by Floppy** [comment]
Good question. I suspect not, as the use case is for private off-github sharing, so the users who need it sharing with are not going to be members of a github team.

But, there's no reason why github teams or orgs couldn't be used as well.

**Comment by Floppy** [comment]
I didn't realise, but this is already possible through the Users interface if you're an admin. I think that might be good enough.

**Comment by Floppy** [comment]
![screen shot 2017-09-05 at 09 32 51](https://user-images.githubusercontent.com/3565/30052396-36803ecc-921d-11e7-8cb0-8cc0808a4e51.png)

![screen shot 2017-09-05 at 09 32 42](https://user-images.githubusercontent.com/3565/30052401-3954994a-921d-11e7-883e-5814bd1953af.png)

![screen shot 2017-09-05 at 09 32 05](https://user-images.githubusercontent.com/3565/30052404-3c6f8798-921d-11e7-9130-e04c8ab1b7f4.png)

**Comment by Floppy** [comment]
I've written this process up on the wiki: https://github.com/theodi/octopub/wiki/Allocating-specific-schemas-to-users
