### ISSUE TITLE
Individual dataset view

### ISSUE THREAD

**Issue by langphil** [theodi/octopub#709]
View a dataset 'collection' on a single page, so that a user can interact with the datasets contents.

View all of the details about a dataset 'collection' on the single page, including:
- metadata
- associated files
- associated schemas
- actions around the dataset 'collections' ('View on Github', 'Download datapackage', 'Subscribe to changes', 'Publish data collection' - for pre-published datasets')

<img width="480" alt="screen shot 2018-02-05 at 15 08 43" src="https://user-images.githubusercontent.com/5029907/35811475-7deedf20-0a86-11e8-846e-b76731b2d270.png">

**Comment by rachelwilson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create dataset view (S3)](https://trello.com/c/DUgoEzBk/159-create-dataset-view-s3)

**Comment by rachelwilson** [comment]
Implemented in Octopub.io
