### ISSUE TITLE
[feature]: use a repo also as container of more than one dataset

### ISSUE THREAD

**Issue by aborruso** [theodi/octopub#71]
Hi,
your great git-data-publisher create a repo for every uploaded dataset.

It would be great to have also the possibility to use a repo as general container (my city open data repo) and to have one folder for every dataset (the city bike sharing parks, the city museums, the city bus stops, etc.).

In this way we will have in some way a good data portal.

Thank you

**Comment by rachelwilson** [comment]
The new version of [octopub.io](https://octopub.io/) has introduced this functionality. Please do experiment, we hope you like it.
