### ISSUE TITLE
(Pre)Published dataset dashboard view

### ISSUE THREAD

**Issue by langphil** [theodi/octopub#718]
Expand upon the existing version of the dashboard table of datasets

Implementing:
- Published status column
- Applied schema name
- Overall validation status - representative of all dataset files
- Action column (Publish, edit, delete, view, download, add files)

<img width="557" alt="screen shot 2018-02-16 at 15 21 52" src="https://user-images.githubusercontent.com/5029907/36314576-259bfc4a-132d-11e8-9954-db21033cda57.png">

**Comment by rachelwilson** [comment]
Implemented in Octopub v2
