### ISSUE TITLE
Navbar - logic and styling

### ISSUE THREAD

**Issue by langphil** [theodi/octopub#722]
Implement new structure, logic and styling for the navbar

- 'Dataset collection' and 'Schemas' should only be 'enabled' for logged in users
- 'Current page' link should have the 'color' orange

<img width="913" alt="screen shot 2018-02-19 at 16 57 18" src="https://user-images.githubusercontent.com/5029907/36389116-fb19f7f4-1595-11e8-8ceb-95a4e5a7675f.png">

**Comment by rachelwilson** [comment]
Implemented in Octopub v2
