### ISSUE TITLE
API link errors with NameError

### ISSUE THREAD

**Issue by rachelwilson** [theodi/octopub#832]
1. Click the "API" header menu option
2. Should give the API page but instead returns 500 response with error message "undefined local variable or method `privacy_policy_path'"

Screen shot with stack trace attached
![logged out api link error](https://user-images.githubusercontent.com/6087190/42753938-773644a6-88ea-11e8-8369-5cd17c2a1ba2.png)

**Comment by olivierthereaux** [comment]
This appears to have been fixed.
