### ISSUE TITLE
Add some BETA warnings on homepage and header

### ISSUE THREAD

**Issue by rachelwilson** [theodi/octopub#833]
To make it clear about the level of support to expect and robustness of the new version we'd like to scatter some "This product is in BETA" warnings around before we go live

On the homepage and in the header at least

**Comment by langphil** [comment]
Fixed by https://github.com/theodi/octopub/pull/851

**Comment by rachelwilson** [comment]
Released to live https://github.com/theodi/octopub/pull/850
