### ISSUE TITLE
Status of an unpublished collection to remain "unpublished" even after editing

### ISSUE THREAD

**Issue by rachelwilson** [theodi/octopub#834]
The new status of "revised" should only apply to published collections.

Until a collection is published the only status it should have is unpublished, no matter how many times it is edited.

**Comment by langphil** [comment]
Unpublished collection now maintains a status of 'unpublished' until it is published to Github. Once published an edit will attribute a 'revised' status to the collection - https://github.com/theodi/octopub/commit/1664da926801948b4c05668b6ea2a6e9923310b7

**Comment by langphil** [comment]
Unpublished collection now maintains the attribute 'unpublished' when an 'edit' is made to it. Once published to Github the collection will have the attribute 'revised' when an 'edit' is made to it. https://github.com/theodi/octopub/pull/840
