### ISSUE TITLE
file link in edit collection for pre-published files needs to get file from s3

### ISSUE THREAD

**Issue by rachelwilson** [theodi/octopub#843]
1.  Go to edit a collection
2. In each section per uploaded file there is a link to download the file.
3. For unpublished files, the link should point to s3 instead of github

File links in the old version of octopub used to download the file from github.  Now we have the new pre-published status we need to download files from s3 - for the pre-published files at least.

**Comment by rachelwilson** [comment]
I'd say, remove the link first and deploy that, and then depending on other priorities come back to this issue and implement it fully

**Comment by langphil** [comment]
Having checked it seems that files are being downloaded from S3 already. Will confirm with you that I am looking at the correct element.

**Comment by langphil** [comment]
Fixed by https://github.com/theodi/octopub/pull/867
