### ISSUE TITLE
New layout: content spills out of divs on mobile

### ISSUE THREAD

**Issue by chris48s** [theodi/octopub#854]
### Expected Behaviour

Content should stay in its box when screen resolution is narrow (e.g: portrait mode on phone)

### Current Behaviour (for problems)

Screenshots from my (android) device:

![screenshot_20180725-092157](https://user-images.githubusercontent.com/6025893/43188774-df9f63fc-8fec-11e8-9b90-4a30dc01286e.png)

![screenshot_20180725-092202](https://user-images.githubusercontent.com/6025893/43188778-e124a520-8fec-11e8-9220-ff43fae5f15d.png)

### Steps to Reproduce (for problems)

1. Look at website on a phone (or 'responsive design mode' in your desktop browser of choice)
2. Scroll to the bottom of the page

### Your Environment

Reproducible in a range of environments

**Comment by olivierthereaux** [comment]
The UI design of Octopub is not meant to be mobile-friendly, but... the implementation could still be better.

**Comment by langphil** [comment]
https://github.com/theodi/octopub/pull/866 will fix this for the signed out homepage

Ocotpub is a tool orientated for desktop publishing, however, a mobile friendly homepage is sensible.

*Design Images* 
<img width="375" alt="screen shot 2018-07-26 at 22 28 24" src="https://user-images.githubusercontent.com/5029907/43289800-9a881cfc-911b-11e8-89d3-c791da7af31d.png">
<img width="371" alt="screen shot 2018-07-26 at 22 28 35" src="https://user-images.githubusercontent.com/5029907/43289804-9f0993dc-911b-11e8-86b2-180d657517f7.png">
