### ISSUE TITLE
octopub.io/api is showing a fatal error message

### ISSUE THREAD

**Issue by peterkwells** [theodi/octopub#858]
https://octopub.io/api

via Ross J https://twitter.com/rossjones/status/1021998873278115840

<img width="1038" alt="screen shot 2018-07-25 at 11 01 50" src="https://user-images.githubusercontent.com/6670237/43194425-341e41c0-8ffa-11e8-89ac-5b250a6eb4fd.png">

**Comment by rachelwilson** [comment]
Fixed
