### ISSUE TITLE
On-hover href for [...] action link in collection list is set to "example.com"

### ISSUE THREAD

**Issue by peterkwells** [theodi/octopub#864]
When viewing an (unpublished) collection of data and mouse-hovering over the "..." in the Actions column my browser is showing the URL as redirecting to https://example.com

### Expected Behaviour
It should show a meaningful URL that tells the user what page to expect next

### Desired Behaviour (for improvement suggestions only)
> if relevant include images or hyperlinks to other resources that clarify the enhancement you're seeking

### Current Behaviour (for problems)
It shows https://example.com

<img width="1297" alt="screen shot 2018-07-25 at 20 03 10" src="https://user-images.githubusercontent.com/6670237/43250419-3338b93c-90b5-11e8-88bf-949b0156712a.png">

### Steps to Reproduce (for problems)
see https://octopub.io/collection/10

### Your Environment

Up-to-date Chrome, up-to-date macOS, on desktop

**Comment by olivierthereaux** [comment]
Thanks for this @peterkwells - I can reproduce the issue. Not sure what the image you attached to your report means, however. Mistaken copy-paste?

**Comment by olivierthereaux** [comment]
<img width="1384" alt="screenshot 2018-07-26 08 53 57" src="https://user-images.githubusercontent.com/604646/43249036-86b0696a-90b1-11e8-92ac-013fd373327a.png">

**Comment by olivierthereaux** [comment]
<img width="1151" alt="screenshot 2018-07-26 08 58 17" src="https://user-images.githubusercontent.com/604646/43249221-11164a20-90b2-11e8-90ba-d15a955776d3.png">

**Comment by olivierthereaux** [comment]
If we are going to use an a href for this (grumble grumble javascript) then the href should point to the individual dataset / schema listed in the table, rather than example.com - as a matter of accessibility.

See e.g. https://github.com/theodi/octopub/blob/2a52ed8b543d8760a9c373effabbb6d144060bc3/app/views/layouts/_nav.html.erb#L8 for the right way to do it.

**Comment by peterkwells** [comment]
d'oh! screenshot fixed, that other one was when I was promoting ProjectsbyIF's recruitment drive :)

https://twitter.com/peterkwells/status/1022094641083174912
