### ISSUE TITLE
Octopub website, "Getting started" page, "Read more about licenses" link broken

### ISSUE THREAD

**Issue by matthieubosquet** [theodi/octopub#871]
### Expected Behaviour

"Read more about licenses here" should probably point to https://theodi.org/article/publishers-guide-to-open-data-licensing/ 

### Current Behaviour

The href attribute of the anchor tag has no value (therefore points to itself https://octopub.io/getting-started)

### Steps to Reproduce

1. Open https://octopub.io/getting-started in a browser (Using Chrome 68 on MacOS here)
2. Open the developer tools of browser (Command+Shift+i or similar) and select an element to inspect (Command+alt+c or similar)
3. Under "Open Data > Basics of Open Data > Why do I have to choose a licence?", inspect "here" in "Read more about licenses here"
3. You should see an anchor tag with an empty href attribute

### Environment

* Browser: Chrome Version 68.0.3440.106
* Desktop: MacOS High Sierra 10.13.6

**Comment by rachelwilson** [comment]
Ah yes, i see what you mean.  It should actually open the getting started page concertina to the section About > Open Data > Making Data Open / Licensing.

We should fix that.  Thanks for raising this.
