### ISSUE TITLE
"View on Github" link in collection view

### ISSUE THREAD

**Issue by olivierthereaux** [theodi/octopub#956]
The link to "view on github" when viewing a collection points to the github repo. It should point to the github.io web page instead.

How to reproduce:

1. log in
2. Pick a data collection
3. View that collection
4. click on the "View on Github" link

Desired behaviour: link should go to https://[user].github.io/[repository]
Actual behaviour: link goes to https://github.com/[user]/[repository] (e.g. https://github.com/olivierthereaux/octopub-tutorial)

Aggravating factors: the generated repository is a little "bare", with no description nor LICENCE file present.

Suggested fix:
1. Change the link in the collection view
2. Ideally, make the repo a little richer
  * Use the collection description as repo description
  * Add a few lines to README.md with a link to the generated github.io webpage

**Comment by caiwilliamson** [comment]
Fixed in #978
