### ISSUE TITLE
Can't add a second data file

### ISSUE THREAD

**Issue by richardjpope** [theodi/octopub#998]
> Please provide a general summary of the issue in the Issue Title above
> fill out the headings below as applicable to the issue you are reporting,
> deleting as appropriate but offering us as much detail as you can to help us resolve the issue

### Expected Behaviour
Once a single csv has been published, it should be possible to go back and add a second one.

### Current Behaviour (for problems)
> What currently happens that isn't expected behaviour?

The "add another file" link on the colleciton page has an empty href:

<div class="col-md-5 col-md-offset-7 icon-blue" style="text-align: right;">
    <i class="fa fa-plus-circle"></i>
    <a href="">Add another file</a>
  </div>

### Your Environment
macos, safari 10.15.6 Beta (19G46c)

**Comment by caiwilliamson** [comment]
Thank you Richard. I'll push a fix for this.
